name: 'Deploy to AWS s3'
description: 'Deploy static website via AWS S3'
inputs:  
  bucket-region:
    description: 'AWS Region'
    required: true
    default: 'us-east-1'
  bucket:
    description: 'S3 Bucket Name'
    required: true
  dist-folder:
    description: 'Folder with static files to deploy'
    required: true
outputs:
  website-url:
    description: 'URL of the deployed website'

runs:
  using: 'node20'
  main: 'main.js'